owner: gabrielegenovese
repo: cappuccino-uptime

sites:
  - name: "Host: cappuccino"
    check: "tcp-ping"
    url: cappuccino.ovh
    port: 2222
  - name: Immich
    url: https://photos.cappuccino.ovh
  - name: NextCloud
    url: https://cloud.cappuccino.ovh
  - name: matrix
    url: https://matrix.cappuccino.ovh
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Matrix_icon.svg/512px-Matrix_icon.svg.png?20210502154855
  - name: minecraft
    check: "tcp-ping"
    url: mc.cappuccino.ovh
    port: 25565
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon-32x32.png

assignees:
  - gabrielegenovese
  - sxmg0
  
status-website:
  cname: uptime.cappuccino.ovh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cappuccino Uptime
  introTitle: "Cappuccino uptime board"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
